# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proj2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proj2.proto',
  package='proj2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bproj2.proto\x12\x05proj2\"\"\n\x05Initi\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03ori\x18\x02 \x01(\x05\"3\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05\x63lock\x18\x02 \x01(\x05\x12\x0b\n\x03ori\x18\x03 \x01(\x05\"2\n\x05Reply\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05\x63lock\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\x05\"\'\n\x08SerError\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"3\n\x07Release\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03ori\x18\x02 \x01(\x05\x12\r\n\x05\x63lock\x18\x03 \x01(\x05\"P\n\tBroadcast\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03ori\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\x05\x12\x0b\n\x03\x61mt\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\x62\x06proto3'
)




_INITI = _descriptor.Descriptor(
  name='Initi',
  full_name='proj2.Initi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Initi.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Initi.ori', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='proj2.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Request.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock', full_name='proj2.Request.clock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Request.ori', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=109,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='proj2.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Reply.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock', full_name='proj2.Reply.clock', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='proj2.Reply.dest', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=161,
)


_SERERROR = _descriptor.Descriptor(
  name='SerError',
  full_name='proj2.SerError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.SerError.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proj2.SerError.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=202,
)


_RELEASE = _descriptor.Descriptor(
  name='Release',
  full_name='proj2.Release',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Release.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Release.ori', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock', full_name='proj2.Release.clock', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=255,
)


_BROADCAST = _descriptor.Descriptor(
  name='Broadcast',
  full_name='proj2.Broadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Broadcast.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Broadcast.ori', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='proj2.Broadcast.dest', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amt', full_name='proj2.Broadcast.amt', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock', full_name='proj2.Broadcast.clock', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=337,
)

DESCRIPTOR.message_types_by_name['Initi'] = _INITI
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['SerError'] = _SERERROR
DESCRIPTOR.message_types_by_name['Release'] = _RELEASE
DESCRIPTOR.message_types_by_name['Broadcast'] = _BROADCAST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Initi = _reflection.GeneratedProtocolMessageType('Initi', (_message.Message,), {
  'DESCRIPTOR' : _INITI,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Initi)
  })
_sym_db.RegisterMessage(Initi)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Reply)
  })
_sym_db.RegisterMessage(Reply)

SerError = _reflection.GeneratedProtocolMessageType('SerError', (_message.Message,), {
  'DESCRIPTOR' : _SERERROR,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.SerError)
  })
_sym_db.RegisterMessage(SerError)

Release = _reflection.GeneratedProtocolMessageType('Release', (_message.Message,), {
  'DESCRIPTOR' : _RELEASE,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Release)
  })
_sym_db.RegisterMessage(Release)

Broadcast = _reflection.GeneratedProtocolMessageType('Broadcast', (_message.Message,), {
  'DESCRIPTOR' : _BROADCAST,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Broadcast)
  })
_sym_db.RegisterMessage(Broadcast)


# @@protoc_insertion_point(module_scope)
