# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proj2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proj2.proto',
  package='proj2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bproj2.proto\x12\x05proj2\"M\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03ori\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\x05\x12\r\n\x05\x63lock\x18\x04 \x01(\x05\x12\x0c\n\x04mess\x18\x05 \x01(\t\"\"\n\x05Initi\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03ori\x18\x02 \x01(\x05\"\'\n\x08SerError\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"$\n\x07Release\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0b\n\x03ori\x18\x03 \x01(\x05\"&\n\tBroadcase\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0b\n\x03ori\x18\x04 \x01(\x05\"$\n\x07Request\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0b\n\x03ori\x18\x05 \x01(\x05\"(\n\x0bTransaction\x12\x0c\n\x04type\x18\x05 \x01(\x05\x12\x0b\n\x03ori\x18\x06 \x01(\x05\x62\x06proto3'
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='proj2.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Event.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Event.ori', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='proj2.Event.dest', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock', full_name='proj2.Event.clock', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mess', full_name='proj2.Event.mess', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=99,
)


_INITI = _descriptor.Descriptor(
  name='Initi',
  full_name='proj2.Initi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Initi.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Initi.ori', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=135,
)


_SERERROR = _descriptor.Descriptor(
  name='SerError',
  full_name='proj2.SerError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.SerError.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proj2.SerError.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=176,
)


_RELEASE = _descriptor.Descriptor(
  name='Release',
  full_name='proj2.Release',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Release.type', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Release.ori', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=214,
)


_BROADCASE = _descriptor.Descriptor(
  name='Broadcase',
  full_name='proj2.Broadcase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Broadcase.type', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Broadcase.ori', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=254,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='proj2.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Request.type', index=0,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Request.ori', index=1,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=292,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='proj2.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj2.Transaction.type', index=0,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='proj2.Transaction.ori', index=1,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=334,
)

DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Initi'] = _INITI
DESCRIPTOR.message_types_by_name['SerError'] = _SERERROR
DESCRIPTOR.message_types_by_name['Release'] = _RELEASE
DESCRIPTOR.message_types_by_name['Broadcase'] = _BROADCASE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Event)
  })
_sym_db.RegisterMessage(Event)

Initi = _reflection.GeneratedProtocolMessageType('Initi', (_message.Message,), {
  'DESCRIPTOR' : _INITI,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Initi)
  })
_sym_db.RegisterMessage(Initi)

SerError = _reflection.GeneratedProtocolMessageType('SerError', (_message.Message,), {
  'DESCRIPTOR' : _SERERROR,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.SerError)
  })
_sym_db.RegisterMessage(SerError)

Release = _reflection.GeneratedProtocolMessageType('Release', (_message.Message,), {
  'DESCRIPTOR' : _RELEASE,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Release)
  })
_sym_db.RegisterMessage(Release)

Broadcase = _reflection.GeneratedProtocolMessageType('Broadcase', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASE,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Broadcase)
  })
_sym_db.RegisterMessage(Broadcase)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Request)
  })
_sym_db.RegisterMessage(Request)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'proj2_pb2'
  # @@protoc_insertion_point(class_scope:proj2.Transaction)
  })
_sym_db.RegisterMessage(Transaction)


# @@protoc_insertion_point(module_scope)
